#!/bin/sh

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
	echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

check_run vimrc "vim -T dumb -c 'PlugUpdate' -c 'qa'"
check_run Brewfile "brew bundle --file=Brewfile"
check_run Brewfile.casks "brew bundle --file=Brewfile.casks"

echo ">>> Running rcup..."
rcup -v | grep -v identical
