#!/bin/sh

set -e

latest_ruby_version(){
  asdf list ruby | tail -1
}

echo "Installing latest Ruby (version $(latest_ruby_version))..."
asdf install ruby "$(latest_ruby_version)"

asdf global ruby "$(latest_ruby_version)"
